
INSERT INTO video_games(Name, Genre, Price, Developer, Publisher, Rating) VALUES("Minecraft", "Action & Adventure", 29.99, "Mojang", "Microsoft", 4.8),
("Monster Hunter World", "Action & Adventure", 29.99, "Capcom", "Capcom", 4.4),
("Super Mario Oddysey", "Platformer", 59.99, "Nintendo", "Nintendo", 4.8),
("Super Mario Bros Wonder", "Platformer", 59.99, "Nintendo", "Nintendo", 4.6),
("Legend of Zelda: Tears of the Kingdom", "Action & Adventure", 59.99, "Nintendo", "Nintendo", 4.8),
("Legend of Zelda: Breath of the Wild", "Action & Adventure", 59.99, "Nintendo", "Nintendo", 4.9),
("Metal Gear Solid", "Stealth", 49.99, "Kojima Productions", "Konami", 4.7),
("Metal Gear Solid 2: Sons of Liberty", "Stealth", 49.99, "Kojima Productions", "Konami", 4.8),
("Metal Gear Solid 3: Snake Eater", "Stealth", 49.99, "Kojima Productions", "Konami", 4.5),
("Metal Gear Solid 4: Guns of the Patriots", "Stealth", 49.99, "Kojima Productions", "Konami", 4.7),
("Metal Gear Solid 5: Ground Zeroes", "Stealth", 29.99, "Kojima Productions", "Konami", 3.7),
("Metal Gear Solid 5: The Phantom Pain", "Stealth", 59.99,  "Kojima Productions", "Konami", 4.6),
("Pokemon: Scarlet Version", "Role-Playing", 59.99, "Game Freak", "Nintendo", 3.5),
("Pokemon: Violet Version", "Role-Playing", 59.99, "Game Freak", "Nintendo", 3.5),
("Pokemon Legends: Arceus", "Role-Playing", 59.99, "Game Freak", "Nintendo", 4.1),
("Call of Duty: Modern Warfare", "First-Person Shooter", 59.99, "Infinity Ward", "Activision", 4.7),
("Call of Duty: Modern Warfare 2", "First-Person Shooter", 59.99, "Infinity Ward", "Activision", 4.7),
("Call of Duty: Modern Warfare 3", "First-Person Shooter", 59.99, "Infinity Ward", "Activision", 4.4),
("Street Fighter IV", "Fighting", 29.99, "Capcom", "Capcom", 4.6),
("Street Fighter V", "Fighting", 29.99, "Capcom", "Capcom", 3.8),
("Street Fighter VI", "Fighting", 59.99, "Capcom", "Capcom", 4.6);